/*
 * This Java source file was generated by the Gradle 'init' task.
 * and further adjusted by myself
 */
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

public class App {
    public String getGreetingFromApp() {
        return strGreeting;
    }

    private static void getBundle(String[] args) {
        String strLanguage, strCountry;
        if (args.length == 2) {
            strLanguage = args[0];
            strCountry = args[1];
        } else {
            strLanguage = "en";
            strCountry = "US";
        }
        currentLocale = new Locale(strLanguage, strCountry);
        try {
            messages = ResourceBundle.getBundle("MessagesBundle", currentLocale);
        } catch(MissingResourceException e) {
            e.printStackTrace();
            ;
        } finally {
            ;
        }
    }

    private static String getGreetingFromResource() {
        return messages.getString("hello_world");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreetingFromApp());
        getBundle(args);
        System.out.println(getGreetingFromResource());
    }
    private String strGreeting = "Hello world.";

    private static Locale currentLocale = null;
    private static ResourceBundle messages = null;
}
